services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: ${DPSRV_HOME}/rc/secrets/mysql/mysql.env
    ports:
      - "53306:3306"
    volumes:
      - ${DPSRV_HOME}/rc/secrets/mysql/conf.d/:/etc/mysql/conf.d1/
      - ${DPSRV_HOME}/srv/mysql/:/var/lib/mysql/
      - /etc/localtime:/etc/localtime:ro
    restart: "no"
