services:
  dpsrv-mysql:
    container_name: dpsrv-mysql-${tag:-latest}
    image: dpsrv/mysql:${tag:-latest}
    build: .
    hostname: $HOSTNAME.dpsrv.me
    env_file:
      - ${DPSRV_HOME}/rc/secrets/mysql/mysql.env
      - ${DPSRV_HOME}/rc/secrets/local/${HOSTNAME}/${HOSTNAME}.env
    ports:
      - "53306:3306"
    volumes:
      - ${DPSRV_HOME}/rc/secrets/mysql/conf.d/:/etc/mysql/conf.d/
      - ${DPSRV_NODE_HOME}/srv/mysql/:/var/lib/mysql/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
